### ISSUE TITLE
implemented grid actions and filtration functionality.

### ISSUE THREAD

**Issue by rudresh8440** [infurotech/erp#10]

**Comment by agupta-infuro** [comment]
Filter on the grid should support following functionalities

1. Add the column level, developers should be able to define the required filter flag
2. Upto 5 filters can be shown initially and more should be added for user to select. Similar to jira
3. Users/Custom filter with template should be supported
4. User should be able to save filters and it should automatically create a new tab for saved filters
5. When filter is applied even should be raised to parent component to get the filtered data from server
